authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product')
]

mainapp/models.py
from django.db import models

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='имя')
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc =  models.CharField(max_length=64, verbose_name='краткое описание', blank=True)
    description = models.TextField(blank=True, verbose_name='описание')
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(verbose_name='Кол-во на складе', default=0)

    def __str__(self):
        return f'{self.name} ({self.category})'

mainapp/views.py
from django.shortcuts import render
import datetime
import os
from django.conf import settings
import json

from mainapp.models import ProductCategory, Product

from django.shortcuts import get_object_or_404
from basketapp.models import Basket

import random

# Create your views here.

def get_basket(user):
    basket = []
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return []


def get_hot_product():
    products_list = Product.objects.all()

    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products

def main(request):
    title = 'Главная'
    products = Product.objects.all()[:4]

    content = {
        'title': title,
        'products': products,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    print(pk)
    tittel = 'Продукты'
    links_menu = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            product_list = Product.objects.all().order_by('price')
            category_item = {'name': 'все', 'pk': 0}
        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            product_list = Product.objects.filter(category=category_item)
        content = {
            'title': tittel,
            'links_menu': links_menu,
            'category': category_item,
            'products': product_list,
            'basket': get_basket(request.user),
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    content = {
        'title': tittel,
        'links_menu': links_menu,
        'same_products': same_products,
        'hot_product': hot_product,
        'basket': get_basket(request.user),
    }
    #print(basket)
    return render(request, 'mainapp/products.html', content)


def contact(request):
    title = 'Контакты'
    locations = []
    with open(os.path.join(settings.BASE_DIR ,'contacts.json'), encoding="utf-8") as f:
        locations = json.load(f)
    content = {
        'title': title,
        'locations': locations,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/contact.html', content)


def product(request, pk):
    content = {
        'title': 'продукты',
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
	<li>
		<a href="{% url 'mainapp:category' 0 %}" {% if request.resolver_match.kwargs.pk == 0 %} class="active" {% endif %}>
			все
		</a>
	</li>
	{% for link in links_menu %}
		<li><a href="{% url 'mainapp:category' link.pk %}" {% if request.resolver_match.kwargs.pk == link.pk %} class="active" {% endif %}>
			{{link.name}}
		</a></li>
	{% endfor %}

</ul>

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'main' %}"  {% if request.resolver_match.url_name == 'main' %} class="active" {% endif %} >
        домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:products' %}" {% if request.resolver_match.namespace == 'products' %} class="active" {% endif %}>
        продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}" {% if request.resolver_match.url_name == 'contact' %} class="active" {% endif %}>
        контакты
        </a>
    </li>

    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'auth:edit' %}">
        {{ user.first_name|default:'Пользователь' }}
        </a>
    </li>
    {% endif %}


    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">
                выход
            </a>
        {% else %}
            <a href="{% url 'auth:login' %}">
                вход
            </a>
        {% endif %}
    </li>
</ul>

<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket%}
        {{ basket.0.total_cost|floatformat:0 }} руб
        ({{ basket.0.total_quantity }})
        {% endif %}
    </span>
</a>